---
- name: Configure sshd to trust Vouch SSH CA
  hosts: all
  become: true
  roles:
    - role: vouch_sshd
      vars:
        # Anyone with a cert principal ending in @acme.com can SSH in.
        vouch_allowed_domains:
          - acme.com

        # Additionally, only certs with the "admin" principal can log in
        # as root, and "deploy"/"ci" principals can log in as deploy.
        vouch_authorized_principals:
          root:
            - admin
          deploy:
            - deploy
            - ci
