vouch_ca_public_key: ""

vouch_ca_key_path: /etc/ssh/vouch-ca.pub

vouch_authorized_principals_dir: /etc/ssh/auth_principals

vouch_authorized_principals: {}
#   root:
#     - admin
#   deploy:
#     - deploy
#     - ci

vouch_revoked_keys_path: /etc/ssh/vouch-revoked-keys

vouch_sshd_config_path: /etc/ssh/sshd_config.d/vouch-ca.conf
